apiVersion: apps/v1
kind: Deployment
metadata:
  name: demandgen-nginx-deployment
  labels:
    app: demandgen-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demandgen-nginx
  template:
    metadata:
      labels:
        app: demandgen-nginx
    spec:
      containers:
        - name: demandgen-nginx
          image: genietalk/demandgen_nginx:0.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demandgen-nginx-service
spec:
  selector:
    app: demandgen-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80